### PR TITLE
commenting 'rm -f'

### PR DESCRIPTION
**Pull request by stevebanikrocana**
so that agent doesn't duplicate data when it sees a new link to the same file

### CODE REVIEW

**Comment by m0j0hn** [comment]
Tbc, the reason for the rm is to remove dead links, like links to worker nodes that have gone away - are you sure we want to disable that?
Also, I can imagine making this an option, sort of like a garbage collector - thoughts on that?
Lmk so we can proceed. Thanks!

**Comment by stevebanikrocana** [comment]
Leaving the dead links appears to be harmless.  Dead links simply report a `stat` error in rocana-agent.log, and then rocana-agent happily proceeds to work on the live links.

**Comment by stevebanikrocana** [comment]
Just "thinking out loud" - a better approach might be to modify the script to test for dead links, and only remove those.

**Comment by stevebanikrocana** [comment]
Can we just try commenting the rm line for now?  I'd like to test that to ensure it stops the duplicate events.

**Pull request merged**
